require: rubocop-rspec

Documentation:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false

Metrics/LineLength:
  Max: 100
  AllowHeredoc: true
  AllowURI: true

RSpec/MultipleExpectations:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
